[versions]

# Gradle
gradleVersionsChecker = "0.51.0"

# Jetbrains
kotlin = "2.1.0"
kotlinx-coroutines = "1.9.0"
kotlinx-serialization = "1.7.3"
kotlinx-datetime = "0.6.1"
kotlinx-collectionsImmutable = "0.3.8"
jetbrainsCompose = "1.7.1"
ktor = "3.0.2"

# Jetpack
jetpack-datastore = "1.1.1"
jetpack-paging = "3.3.4"

# Square
sqldelight = "2.0.2"
molecule = "2.0.0"

# Other
multiplatformSettings = "1.3.0"
kermit = "2.0.5"
kotlinCsv = "1.9.3"
kotlinResult = "2.0.0"
appdirs = "1.2.2"
buildKonfig = "0.15.2"
openjfx = "23.0.1"
filekit = "0.8.7"
clikt = "5.0.2"
colorpickerCompose = "1.1.2"
apacheCommons-compress = "1.27.1"
composeRichtext = "1.0.0-alpha02"
cryptography = "0.4.0"
kotlinWrappers-kotlinCss = "1.0.0-pre.839"
jimfs = "1.3.0"

[plugins]
# Gradle Versions Checker
gradle-versions-checker = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsChecker" }

# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Jebrains Compose
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }

# SQLDelight
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }

# BuildKonfig
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }

[libraries]

# KotlinX Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# KotlinX Serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# KotlinX DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# KotlinX Immutable Collections
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collectionsImmutable" }

# Ktor
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Jetpack DatatStore
jetpack-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "jetpack-datastore" }

# Jetpack Paging
jetpack-paging-common = { module = "androidx.paging:paging-common", version.ref = "jetpack-paging" }

# SQLDelight
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-sqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-primitiveAdapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-coroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-dialect-sqlite338 = { module = "app.cash.sqldelight:sqlite-3-38-dialect", version.ref = "sqldelight" }

# Molecule
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }

# Multiplatform Settings
multiplatformSettings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
multiplatformSettings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }

# Kermit
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# kotlin-csv
kotlinCsvJvm = { module = "com.github.doyaaaaaken:kotlin-csv-jvm", version.ref = "kotlinCsv" }

# kotlin-result
kotlinResult = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinResult" }
kotlinResult-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlinResult" }

# AppDirs
appdirs = { module = "net.harawata:appdirs", version.ref = "appdirs" }

# JavaFX
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "openjfx" }
javafx-controls = { module = "org.openjfx:javafx-controls", version.ref = "openjfx" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "openjfx" }
javafx-media = { module = "org.openjfx:javafx-media", version.ref = "openjfx" }
javafx-swing = { module = "org.openjfx:javafx-swing", version.ref = "openjfx" }
javafx-web = { module = "org.openjfx:javafx-web", version.ref = "openjfx" }

# FileKit
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }

# Clikt
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

# ColorPicker Compose
colorpickerCompose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "colorpickerCompose" }

# ColorPicker Compose
apacheCommons-compress = { module = "org.apache.commons:commons-compress", version.ref = "apacheCommons-compress" }

# compose-richtext
composeRichtext-ui-material3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "composeRichtext" }
composeRichtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "composeRichtext" }

# cryptography-kotlin
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core", version.ref = "cryptography" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk", version.ref = "cryptography" }

# Kotlin js wrappers
kotlinWrappers-kotlinCss = { module = "org.jetbrains.kotlin-wrappers:kotlin-css", version.ref = "kotlinWrappers-kotlinCss" }

# Jimfs
jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }
